name: Azure Machine Learning job 

on:
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        
    - name: Install Flake8
      run: |
        python -m pip install flake8
        
    - name: Run linting tests
      run: | 
        flake8 src/model/
        
    - name: Running Unit Test Cases
      run: | 
        python test/test_train.py
        
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml -g ml-workload -w ml-research 


